<?php

use \Drupal\Core\Form\FormStateInterface;

function cambiarFormulario_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id){
    ksm($form);
    ksm($form_state);
    dpm($form_id);

    if ($form_id == 'node_article_edit_form') {
        $form['title']['widget']['0']['value']['#placeholder'] = "test placeholder";
        $form['field_test']['#access'] = false;
        if ($form['field_button']['widget']['value'] == 1 ) {
            $form['field_test']['#access'] = true;

        }
    }

    
    if ($form_id == 'node_page_form') {
        $form['title']['widget']['0']['value']['#placeholder'] = "test placeholder 2";
    }
}